#### Importando Bibliotecas

In [1]:
# Importando bibliotecas

import pandas as pd
import numpy as np

In [2]:
# Carregando dataset tratado
df = pd.read_csv("../data/processed/datatran2025.csv")

##### Análise Exploratória de Dados(EDA) :

In [3]:
# Verificando os dados em cada coluna para achar valores nulos 
# Além de verificar colunas que não serão relevantes para a análise.

print("--- Primeiras Linhas ---")
display(df.head(5)) # O display() deixa a tabela mais bonita no Jupyter que o print()

print("\n--- Lista de Colunas ---")
print(df.columns)

print("\n--- Resumo Estatístico (Dados Numéricos e Categóricos) ---")
display(df.describe(include="all"))

print("\n--- Contagem de Valores Nulos (NaN) ---")
print(df.isnull().sum())

--- Primeiras Linhas ---

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,652493,1/1/2025,quarta-feira,6:20:00,SP,116,225,GUARULHOS,Reação tardia ou ineficiente do condutor,Tombamento,...,0.0,0.0,1.0,1.0,2.0,-23.0,NaN,NaN,NaN,NaN
1,652519,1/1/2025,quarta-feira,7:50:00,CE,116,546,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,652522,1/1/2025,quarta-feira,8:45:00,PR,369,88,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,652544,1/1/2025,quarta-feira,11:00:00,PR,116,74,CAMPINA GRANDE DO SUL,Reação tardia ou ineficiente do condutor,Saída de leito carroçável,...,0.0,4.0,0.0,1.0,2.0,-25.0,NaN,NaN,NaN,NaN
4,652549,1/1/2025,quarta-feira,9:30:00,MG,251,471,FRANCISCO SA,Velocidade Incompatível,Colisão frontal,...,1.0,1.0,2.0,2.0,4.0,-16.0,NaN,NaN,NaN,NaN

--- Lista de Colunas ---
Index(['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km',
       'municipio', 'causa_acidente', 'tipo_acidente',
       'classificacao_acidente', 'fase_dia', 'sentido_via',
       'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo',
       'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos',
       'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional',
       'delegacia', 'uop'],
      dtype='object')

--- Resumo Estatístico (Dados Numéricos e Categóricos) ---

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
count,72524.000000,72524,72524,72524,72524,72524.000000,72524.000000,45851,45851,45851,...,45851.000000,45851.000000,45851.000000,45851.000000,45851.000000,45851.000000,32.000000,25,24,24
unique,NaN,365,7,1412,27,NaN,NaN,1749,69,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,20,21
top,NaN,12/20/2025,sábado,19:00:00,MG,NaN,NaN,DUQUE DE CAXIAS,Ausência de reação do condutor,Colisão traseira,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SPRF-MG,DEL13-MG,UOP01-DEL13-MG
freq,NaN,285,11554,1060,9570,NaN,NaN,831,7689,9405,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,3,3
mean,700865.439579,NaN,NaN,NaN,NaN,208.500993,259.851511,NaN,NaN,NaN,...,0.254084,1.061438,0.390395,1.122593,1.982923,-17.716713,-46.468750,NaN,NaN,NaN
std,26971.368196,NaN,NaN,NaN,NaN,128.570311,227.925051,NaN,NaN,NaN,...,0.581202,1.846154,0.818434,1.049691,1.087428,7.671723,6.455727,NaN,NaN,NaN
min,652468.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,1.000000,-33.000000,-60.000000,NaN,NaN,NaN
25%,672801.750000,NaN,NaN,NaN,NaN,101.000000,76.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,1.000000,1.000000,-23.000000,-51.000000,NaN,NaN,NaN
50%,703870.500000,NaN,NaN,NaN,NaN,155.000000,192.000000,NaN,NaN,NaN,...,0.000000,1.000000,0.000000,1.000000,2.000000,-20.000000,-47.000000,NaN,NaN,NaN
75%,723723.250000,NaN,NaN,NaN,NaN,319.000000,411.000000,NaN,NaN,NaN,...,0.000000,1.000000,1.000000,1.000000,2.000000,-12.000000,-42.000000,NaN,NaN,NaN
max,755260.000000,NaN,NaN,NaN,NaN,495.000000,1257.000000,NaN,NaN,NaN,...,22.000000,71.000000,18.000000,42.000000,18.000000,4.000000,-34.000000,NaN,NaN,NaN

--- Contagem de Valores Nulos (NaN) ---
id                            0
data_inversa                  0
dia_semana                    0
horario                       0
uf                            0
br                            0
km                            0
municipio                 26673
causa_acidente            26673
tipo_acidente             26673
classificacao_acidente    26673
fase_dia                  26673
sentido_via               26673
condicao_metereologica    26673
tipo_pista                26673
tracado_via               26673
uso_solo                  26673
pessoas                   26673
mortos                    26673
feridos_leves             26673
feridos_graves            26673
ilesos                    26673
ignorados                 26673
feridos                   26673
veiculos                  26673
latitude                  26673
longitude                 72492
regional                  72499
delegacia                 72500
uop                       72500
dtype: int64

In [16]:
# Selecionando as colunas relevantes para a Análise
colunas_selecionadas = [
    'uf',
    'fase_dia',
    'tipo_pista',
    'causa_acidente',
    'tipo_acidente',
    'condicao_metereologica',
    'mortos',
    'feridos'
]

df_modelo = df[colunas_selecionadas].copy()


# Criando a variável Alvo (Target)
# 0 = Sem vítimas
# 1 = Com vítimas (feridos ou mortos)
# Recebe 1 se houver mortos ou feridos, caso contrário 0.
# A condição gera valores booleanos (True/False), que são convertidos para inteiro com astype(int).

df_modelo['target'] = (
    (df_modelo['mortos'] > 0) | (df_modelo['feridos'] > 0)
).astype(int)

# Convertendo em int pois ele por padrão retorna true or false

In [17]:
display(df_modelo)

,uf,fase_dia,tipo_pista,causa_acidente,tipo_acidente,condicao_metereologica,mortos,feridos,target
0,SP,Pleno dia,Múltipla,Reação tardia ou ineficiente do condutor,Tombamento,Céu Claro,0.0,1.0,1
1,CE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,PR,Pleno dia,Dupla,Reação tardia ou ineficiente do condutor,Saída de leito carroçável,Céu Claro,0.0,1.0,1
4,MG,Pleno dia,Simples,Velocidade Incompatível,Colisão frontal,Chuva,0.0,2.0,1
...,...,...,...,...,...,...,...,...,...
72519,PB,Plena Noite,Simples,Ausência de sinalização,Tombamento,Céu Claro,0.0,1.0,1
72520,PA,Pleno dia,Simples,Reação tardia ou ineficiente do condutor,Colisão transversal,Céu Claro,0.0,2.0,1
72521,ES,Plena Noite,Simples,Pedestre andava na pista,Atropelamento de Pedestre,Céu Claro,1.0,0.0,1
72522,MG,Plena Noite,Simples,Ausência de reação do condutor,Colisão frontal,Garoa/Chuvisco,1.0,3.0,1
72523,MG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [23]:
# Verificação da quantidade de Valores Nulos Existentes
print(df_modelo.isnull().sum())

# Tratamento de nulos
df_modelo = df_modelo.dropna()

# Mostra 10 linhas sorteadas aleatoriamente
display(df_modelo.sample(10))

uf                        0
fase_dia                  0
tipo_pista                0
causa_acidente            0
tipo_acidente             0
condicao_metereologica    0
mortos                    0
feridos                   0
target                    0
dtype: int64

,uf,fase_dia,tipo_pista,causa_acidente,tipo_acidente,condicao_metereologica,mortos,feridos,target
50101,RS,Plena Noite,Dupla,Condutor deixou de manter distância do veículo...,Colisão traseira,Chuva,0.0,0.0,0
27408,BA,Plena Noite,Simples,Ultrapassagem Indevida,Colisão lateral sentido oposto,Céu Claro,0.0,4.0,1
34893,GO,Pleno dia,Simples,Ausência de reação do condutor,Colisão com objeto,Céu Claro,1.0,0.0,1
55021,BA,Pleno dia,Simples,Demais falhas mecânicas ou elétricas,Colisão lateral mesmo sentido,Sol,0.0,0.0,0
69430,RJ,Pleno dia,Simples,Reação tardia ou ineficiente do condutor,Colisão frontal,Céu Claro,0.0,3.0,1
68548,ES,Pleno dia,Simples,Desrespeitar a preferência no cruzamento,Colisão transversal,Céu Claro,0.0,2.0,1
32566,RJ,Plena Noite,Múltipla,Reação tardia ou ineficiente do condutor,Colisão traseira,Céu Claro,0.0,1.0,1
24914,AL,Pleno dia,Simples,Animais na Pista,Capotamento,Céu Claro,0.0,1.0,1
6004,PE,Plena Noite,Simples,Transitar na contramão,Colisão lateral mesmo sentido,Céu Claro,0.0,2.0,1
12646,CE,Plena Noite,Simples,Carga excessiva e/ou mal acondicionada,Tombamento,Céu Claro,0.0,1.0,1

In [24]:
# Convertendo as colunas de contagem para inteiros pois após utilizarmos o tratamento de valores nulos...
# O pandas converte toda a coluna para float.

df_modelo['mortos'] = df_modelo['mortos'].astype(int)
df_modelo['feridos'] = df_modelo['feridos'].astype(int)

# 
df_modelo['target'] = df_modelo['target'].astype(int)

display(df_modelo.head())

,uf,fase_dia,tipo_pista,causa_acidente,tipo_acidente,condicao_metereologica,mortos,feridos,target
0,SP,Pleno dia,Múltipla,Reação tardia ou ineficiente do condutor,Tombamento,Céu Claro,0,1,1
3,PR,Pleno dia,Dupla,Reação tardia ou ineficiente do condutor,Saída de leito carroçável,Céu Claro,0,1,1
4,MG,Pleno dia,Simples,Velocidade Incompatível,Colisão frontal,Chuva,0,2,1
5,MT,Pleno dia,Simples,Transitar na contramão,Colisão frontal,Céu Claro,2,0,1
6,RS,Pleno dia,Dupla,Ausência de reação do condutor,Saída de leito carroçável,Céu Claro,0,1,1

In [27]:
# Salvando o resultado do tratamento em um novo arquivo
# index=False evita que o Pandas crie uma coluna extra de números sem nome
df_modelo.to_csv('../data/processed/dados_limpos_para_modelo.csv', index=False)

print("Arquivo salvo com sucesso!")

Arquivo salvo com sucesso!